### ISSUE TITLE
Lch/Lab curves with straight lines changes colors

### ISSUE THREAD

**Issue by cl4cnam** [c-koi/gmic-qt#109]
I opened this image into GIMP 2.10.24 
![couleurs](https://user-images.githubusercontent.com/40176886/114322030-5dcd6c80-9b1e-11eb-8a9b-80a158d45e46.png)
I removed the alpha channel.
I ran G'MIC-Qt 2.9.7 -> Colors -> Curves -> [ColorSpace=Lch, Output...Layer=Disable, Apply...=New...].
I didn't change the curves (They remain straight lines).
The result was this strange image 
![couleursLchBug](https://user-images.githubusercontent.com/40176886/114322352-0d570e80-9b20-11eb-972a-43663dcef65d.png)

If I choose instead "ColorSpace=Lab", the result is 
![couleursLabBug](https://user-images.githubusercontent.com/40176886/114322828-8bb4b000-9b22-11eb-9bdf-57a16eeb8070.png)

(Note : if I do the same with GIMP 2.8 + G'MIC 1.7.9, the result is the original image).

**Comment by dtschump** [comment]
Confirmed. Investigating...

**Comment by dtschump** [comment]
https://github.com/dtschump/gmic/commit/f7549b4f9aa27e18b3573d33dc70e5bc88aef204 should fix this issue.

Could you try 'updating' your filters (with the update button), and see what happens? Thanks.

**Comment by cl4cnam** [comment]
The issue is fixed. Great Job ! Thank you very much indeed !
