### ISSUE TITLE
New CMake doesn't succeed: Qt5LinguistTools missing

### ISSUE THREAD

**Issue by dtschump** [c-koi/gmic-qt#12]
I'm trying to compile gmic-qt with the new CMake from @boudewijnrempt , and I get this error:

```
$:~/work/src/gmic-qt/build$ cmake ../
-- Using CMake version: 3.5.1
Building version:gimp
G'Mic path: ../gmic/src
CMake Error at CMakeLists.txt:46 (find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/dtschump/work/src/gmic-qt/CMakeFiles/CMakeOutput.log".

```

By the way, I can confirm I already have all the required dependencies to compile gmic-qt on my system, using the `.pro` file with `qmake`.
Any idea ?

**Comment by boudewijnrempt** [comment]
Yes -- you're missing a Qt dependency: QtLinguisticTools. It's named differently on the distribution, though. See http://doc.qt.io/qt-5/cmake-manual.html#qt5linguisttools-macros

**Comment by dtschump** [comment]
Not sure why this is dependency. However, I've tried to solve this issue (as suggested here: https://bitsharestalk.org/index.php?topic=9161.0) by installing package `qttools5-dev` (I'm running Ubuntu 16.04). But the error persists.
Still investigating though.

**Comment by dtschump** [comment]
OK, found it, the package `qttools5-dev-tools` was also needed.
Don't ask me why ! ;)
