### ISSUE TITLE
Translation system problem

### ISSUE THREAD

**Issue by cl4cnam** [c-koi/gmic-qt#121]
I can't make the translation system work (French language). I have not made any modification yet.
Here is an extract of https://github.com/c-koi/gmic-qt/blob/master/translations/filters/fr.ts and a screenshot.
![Screenshot_fr ts](https://user-images.githubusercontent.com/40176886/142258105-09ee90f2-cebe-4a48-b5b9-408010f1ef88.jpg)
![Screenshot_gmic_highlight](https://user-images.githubusercontent.com/40176886/142258115-288b4425-5c7c-49fa-b7ae-6843e457bc1a.jpg)

**Comment by c-koi** [comment]
Fixed by c2e11687a0833e5a302f7f4bbd902b20ea735939
Do not forget to (re)run qmake with option TEST_FILTERS_QM=on

**Comment by cl4cnam** [comment]
It works now. Thank you ! :)
