### ISSUE TITLE
Filter refresh button deselects current filter

### ISSUE THREAD

**Issue by dtschump** [c-koi/gmic-qt#136]
When pressing the "filter refresh" button, the plug-in deselect the previously selected filter, even if the filter still exists, with the same name and the same command/preview_command.
It's a bit annoying when I develop a new filter, because each time I want to test the (local) update, I need to reselect the filter.
Previous versions of the plug-in were keeping the current filter selected when possible.
Could it be possible to get this behavior back?

**Comment by c-koi** [comment]
Side-effect of the bug fixed by d3c8c843b9398e109eb0af7b20e9c9d70f5d42e8.
