### ISSUE TITLE
G'MIC-Qt does not compile anymore for Debian 9, Debian 10 and Ubuntu 18.10

### ISSUE THREAD

**Issue by dtschump** [c-koi/gmic-qt#140]
G'MIC-Qt does not compile anymore for Debian 9, Debian 10 and Ubuntu 18.10
(since commits done on 2022/03/30).
It is probably related to the Qt version used : 
- 5.11.13 for Debian 10
- 5.7.1 for Debian 9
- 5.11.1 for Ubuntu 18.10

Attached is a screenshot of the compilation log.
![bug_gmic_qt](https://user-images.githubusercontent.com/10114565/161045491-0e1e5e6a-47e2-4e2f-8412-85b409aa1d22.png)

**Comment by c-koi** [comment]
Fixed by 4654fe15eecac04028b77371dab00e1459369032
