### ISSUE TITLE
SV, zh, and zh_TW translations are missing

### ISSUE THREAD

**Issue by amyspark** [c-koi/gmic-qt#146]
:wave:

It seems that currently the translations for Slovenian, and both Traditional and Simplified Chinese are being skipped:

https://github.com/c-koi/gmic-qt/blob/397d61a0cf8655c1dc7a5d727a7ed6826619722e/CMakeLists.txt#L553-L573

Moreover, the official Simplified Chinese translation is set to French: 

https://github.com/c-koi/gmic-qt/blob/397d61a0cf8655c1dc7a5d727a7ed6826619722e/translations/zh.ts#L6

**Comment by c-koi** [comment]
Fixed by c300f299081cdadcdb5c05d67791ac6ef3785224 and ba428215f068c85a92894e2cb7b1ef093533b24f.
