### ISSUE TITLE
Unwanted capitalization.

### ISSUE THREAD

**Issue by Reptorian1125** [c-koi/gmic-qt#147]
I have a few unwanted capitalization within a few of my own scripts. Here's where you don't want it:

```
#@gui :Format=choice(0,"GIMP Palette - .gpl","Paint.NET Palette - .txt","JASC-PAL - .pal")
```

.gpl becomes .Gpl
.txt becomes .Txt
.pal becomes .Pal

**Comment by dtschump** [comment]
https://github.com/dtschump/gmic/commit/d82f86cda9dd6876f7b632657e9da81482f7a088 fixes this.

**Comment by Reptorian1125** [comment]
Can confirm it is fixed.
