### ISSUE TITLE
Using OpenMP 2.0 and LTO with MSVC

### ISSUE THREAD

**Issue by amyspark** [c-koi/gmic-qt#148]
Hey @c-koi,

I've successfully built G'MIC with OpenMP 2.0 and LTO under the following Windows compilers: MSVC, MSYS Clang 14.0.3, and MSYS GCC 12.1.

This is made possible by the following modules:

- [CheckIPOSupported](https://cmake.org/cmake/help/latest/module/CheckIPOSupported.html#module:CheckIPOSupported), available in CMake 3.9 onwards
- [FindOpenMP](https://cmake.org/cmake/help/latest/module/FindOpenMP.html). I use in particular the cross-compiler support and the language detection, which make CMake 3.10 a requirement.

We at Krita use CMake 3.16, but the project here uses 3.6. Would such an upgrade be OK with you? I already addressed the CImg compatibility with https://github.com/dtschump/CImg/pull/353.

**Comment by c-koi** [comment]
A PR is welcome. Thanks.
