### ISSUE TITLE
Suggestion : make #@gui parsing less strict

### ISSUE THREAD

**Issue by dtschump** [c-koi/gmic-qt#155]
When defining a filter parameter for the G'MIC-Qt plug-in, the following line is not accepted:
~~~
#@gui: Alpha = float(0,0,100)
~~~
We need an extra-space between `#@gui` and `:`, i.e.
~~~
#@gui : Alpha = float(0,0,100)
~~~
Would it be possible that the `#@gui` parser accepts also `#@gui:`?
(applies also for localized filters as `#@gui_fr:`).

**Comment by c-koi** [comment]
Achieved by f63c614.
