### ISSUE TITLE
[Krita plug-in] No optimizations during compilation

### ISSUE THREAD

**Issue by dtschump** [c-koi/gmic-qt#17]
It looks like compiling the plug-in with CMake does not turn the optimizations on, leading in much slower plug-in compared to the GIMP version.
In particular, if I generate the Makefile with cmake, then run:

    $ make VERBOSE=1

I get this kind of compilation command line for each file:

~~~~
[ 94%] Building CXX object CMakeFiles/gmic_krita_qt.dir/home/dtschump/work/src/gmic/src/gmic.cpp.o
/usr/bin/c++   -DGMIC_HOST=krita -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_WIDGETS_LIB -D_IS_LINUX_ -D_IS_UNIX_ -Dcimg_display=1 -Dcimg_use_abort -Dcimg_use_curl -Dcimg_use_fftw3 -Dcimg_use_fftw3_singlethread -Dcimg_use_openmp -Dcimg_use_png -Dcimg_use_rng -Dcimg_use_vt100 -Dcimg_use_zlib -Dgmic_build -Dgmic_gui -Dgmic_is_parallel -I/home/dtschump/work/src/gmic-qt/build -I/home/dtschump/work/src/gmic-qt -I/home/dtschump/work/src/gmic-qt/include -I/home/dtschump/work/src/gmic-qt/../gmic/src -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork  -fopenmp   -fopenmp -fPIC -std=gnu++11 -o CMakeFiles/gmic_krita_qt.dir/home/dtschump/work/src/gmic/src/gmic.cpp.o -c /home/dtschump/work/src/gmic/src/gmic.cpp
~~~~

which clearly exhibits that no `-O3` flag is used (and it should, as done by the default ̀Makefile` and `.pro` file). This is particularly important when compiling the file `gmic.cpp` because it contains all the code that manages the image processing operations, so using `-O3` makes a **huge** difference on the filter performance (even compared to `-O2`!). Note that no optimizations are enabled when compiling the other files as well (though the consequence are probably less visible).

Any idea to fix that?

**Comment by alvinhochun** [comment]
Have you set `CMAKE_BUILD_TYPE` to `Release` or `RelWithDebInfo` though?

**Comment by dtschump** [comment]
(Note: I'm a real novice concerning the use of cmake).

What I've done is just installed `cmake` and `ccmake`, then:
~~~~
dtschump@gmicky:~$ cd work/src/gmic-qt/
dtschump@gmicky:~/work/src/gmic-qt$ mkdir build
dtschump@gmicky:~/work/src/gmic-qt$ cd build/
dtschump@gmicky:~/work/src/gmic-qt/build$ ccmake ..
~~~~
Then `c` for `configure`, and I've set the `GMIC_QT_HOST` to `krita`.
Then  `c` again, and `g` to generate the Makefile.
At no time I've got an option to generate in a `Release` mode or so, but `ccmake` shows me
this, so I suppose it's in `Release` by default:

![gmic_ccmake](https://user-images.githubusercontent.com/10114565/29304625-5183f5cc-8194-11e7-8312-de09845a4335.png)

Then, I typed `make VERBOSE=1` and see no `-O3` options in the command lines used (nor any other optimization flag). I found that the resulting plug-in running on Krita (compiled from the git master) is indeed quite slow compared to the plug-in running on GIMP (which has not been compiled with the `cmake`).

**Comment by dtschump** [comment]
Adding this at line `168`:
~~~
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3")
~~~
seems to solve the problem, but I'm not sure this is the best way to do it.

**Comment by boudewijnrempt** [comment]
On Tue, 15 Aug 2017, David Tschumperlé wrote:

> Adding this at line `168`:
> ~~~
>     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3")
> ~~~
> seems to solve the problem, but I'm not sure this is the best way to do it.
> 

No, that's quite correct.

-- 
Boudewijn Rempt | http://www.krita.org, http://www.valdyas.org

**Comment by dtschump** [comment]
I guess this should also fix the first point described here https://github.com/dtschump/gmic-community/issues/89 !

**Comment by alvinhochun** [comment]
No, that's not quite correct...

When you run cmake you need to add `-DCMAKE_BUILD_TYPE=Release` to the command line to enable release build. By default, cmake should've added `-O3` to the build flags. With ccmake I imagine you will need to define the variable yourself.

The checking on https://github.com/c-koi/gmic-qt/blob/83d95b809f308cb03afc132703b869bfb33979be/CMakeLists.txt#L166 doesn't seem quite correct to me. While `Debug` build should have debugging enabled, `RelWithDebInfo` build should be exactly the same as `Release` build except for not stripping the debug symbols from the binaries. The else block would also be used for any invalid `CMAKE_BUILD_TYPE` (including empty / unset) while it should check for `Release` or `RelWithDebInfo` instead.

What should be done is to explicitly set `CMAKE_BUILD_TYPE` for every build, but if you want to get lazy, you can add a check at the very top of the CMakeLists.txt, to set `CMAKE_BUILD_TYPE` to `Release` if it is empty.

**Comment by boudewijnrempt** [comment]
On Tue, 15 Aug 2017, alvinhochun wrote:

> No, that's not quite correct...
> 
> When you run cmake you need to add `-DCMAKE_BUILD_TYPE=Release` to the command line to enable release build. By default, cmake should've added `-O3` to the build flags. With ccmake I imagine you will need to define the variable yourself.

I think that only sets -O2 ?


-- 
Boudewijn Rempt | http://www.krita.org, http://www.valdyas.org

**Comment by dtschump** [comment]
Option `-O3` is really recommended, at least for compiling file `gmic.cpp`.

**Comment by alvinhochun** [comment]
> > On Tue, 15 Aug 2017, alvinhochun wrote:
> >  No, that's not quite correct...
> > 
> >  When you run cmake you need to add `-DCMAKE_BUILD_TYPE=Release` to the command line to enable release build. By default, cmake should've added `-O3` to the build flags. With ccmake I imagine you will need to define the variable yourself.
> 
> I think that only sets -O2 ?

Just briefly checked the copy of CMake I have here, apparently it is `-O2 -g` for `RelWithDebInfo` and `-O3` for `Release`, which isn't exactly what I expected.

Anyway, if you want to set `-O3` for `RelWithDebInfo`, it'll need to actually replace the -O2` flag, instead of simply appending `-O3`.

**Comment by alvinhochun** [comment]
> Option -O3 is really recommended, at least for compiling file gmic.cpp.

For `RelWithDebInfo`, it might be a good idea to only set `-O3` for `gmic.cpp` and keep `-O2` for others, because `-O3` makes the debug symbols even less useful than with `-O2`..

**Comment by dtschump** [comment]
Using `cmake` instead of `ccmake` doesn't solve the problem, no optimization flags are turned on by default, even in `Release` mode (see log below), if I don't add the line mentionned above. This is really a problem. I didn't tweaked `cmake` or environment variables, just installed it from my package manager (on Ubuntu 16.04). It means that if someone else is using `cmake` to compile `gmic-qt`, he won't have the optimizations turned on. 
Without optimizations, `gmic-qt` becomes almost unusable on large images.

~~~~
dtschump@gmicky:~/work/src/gmic-qt/build$ cmake -DGMIC_QT_HOST=krita ..
-- Using CMake version: 3.5.1
Building version:krita
G'Mic path: ../gmic/src
-- Found FFTW3 
-- FFTW Found Version: 
G'Mic: using OpenMP
Release build
-- 
-- The following OPTIONAL packages have been found:

 * PkgConfig
 * CURL
 * OpenMP , A low-level parallel execution library , <http://openmp.org/wp/>
   Optionally used by gmic-qt

-- The following REQUIRED packages have been found:

 * Qt5Core
 * Qt5Gui
 * Qt5Widgets
 * Qt5Network
 * Qt5 (required version >= 5.2.0)
 * Qt5LinguistTools
 * PNG
 * ZLIB
 * FFTW3

-- Configuring done
-- Generating done
-- Build files have been written to: /home/dtschump/work/src/gmic-qt/build

dtschump@gmicky:~/work/src/gmic-qt/build$ make VERBOSE=1

(...)

[ 34%] Building CXX object CMakeFiles/gmic_krita_qt.dir/src/GmicStdlibParser.cpp.o
/usr/bin/c++   -DGMIC_HOST=krita -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_WIDGETS_LIB -D_IS_LINUX_ -D_IS_UNIX_ -Dcimg_display=1 -Dcimg_use_abort -Dcimg_use_curl -Dcimg_use_fftw3 -Dcimg_use_fftw3_singlethread -Dcimg_use_openmp -Dcimg_use_png -Dcimg_use_rng -Dcimg_use_vt100 -Dcimg_use_zlib -Dgmic_build -Dgmic_gui -Dgmic_is_parallel -I/home/dtschump/work/src/gmic-qt/build -I/home/dtschump/work/src/gmic-qt -I/home/dtschump/work/src/gmic-qt/include -I/home/dtschump/work/src/gmic-qt/../gmic/src -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork  -fopenmp   -fopenmp -fPIC -std=gnu++11 -o CMakeFiles/gmic_krita_qt.dir/src/GmicStdlibParser.cpp.o -c /home/dtschump/work/src/gmic-qt/src/GmicStdlibParser.cpp

(...)
~~~~

No `-O2` or `-O3`. At a result, the compilation is fast, but the plug-in is slow :(

**Comment by alvinhochun** [comment]
Have you added `-DCMAKE_BUILD_TYPE=Release` to the `cmake` command?

**Comment by dtschump** [comment]
Adding this option doesn't change anything.
The CMake actually worked in Release mode in my previous attempt.
Here is the new log:

~~~~
dtschump@gmicky:~/work/src/gmic-qt/build$ cmake -DCMAKE_BUILD_TYPE=Release -DGMIC_QT_HOST=krita ..
-- Using CMake version: 3.5.1
Building version:krita
G'Mic path: ../gmic/src
-- Found FFTW3 
-- FFTW Found Version: 
G'Mic: using OpenMP
Release build
-- 
-- The following OPTIONAL packages have been found:

 * PkgConfig
 * CURL
 * OpenMP , A low-level parallel execution library , <http://openmp.org/wp/>
   Optionally used by gmic-qt

-- The following REQUIRED packages have been found:

 * Qt5Core
 * Qt5Gui
 * Qt5Widgets
 * Qt5Network
 * Qt5 (required version >= 5.2.0)
 * Qt5LinguistTools
 * PNG
 * ZLIB
 * FFTW3

-- Configuring done
-- Generating done
-- Build files have been written to: /home/dtschump/work/src/gmic-qt/build

dtschump@gmicky:~/work/src/gmic-qt/build$ make VERBOSE=1

(...)
[ 43%] Building CXX object CMakeFiles/gmic_krita_qt.dir/src/FolderParameter.cpp.o
/usr/bin/c++   -DGMIC_HOST=krita -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_WIDGETS_LIB -D_IS_LINUX_ -D_IS_UNIX_ -Dcimg_display=1 -Dcimg_use_abort -Dcimg_use_curl -Dcimg_use_fftw3 -Dcimg_use_fftw3_singlethread -Dcimg_use_openmp -Dcimg_use_png -Dcimg_use_rng -Dcimg_use_vt100 -Dcimg_use_zlib -Dgmic_build -Dgmic_gui -Dgmic_is_parallel -I/home/dtschump/work/src/gmic-qt/build -I/home/dtschump/work/src/gmic-qt -I/home/dtschump/work/src/gmic-qt/include -I/home/dtschump/work/src/gmic-qt/../gmic/src -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork  -fopenmp -O3 -DNDEBUG   -fopenmp -fPIC -std=gnu++11 -o CMakeFiles/gmic_krita_qt.dir/src/FolderParameter.cpp.o -c /home/dtschump/work/src/gmic-qt/src/FolderParameter.cpp
(...)

~~~~

**Comment by alvinhochun** [comment]
Well, I do see `-O3` in the compiler flags, which means it does work :)

**Comment by alvinhochun** [comment]
By the way, the `Release build` line in the output is actually printed by an incorrect check in the CMakeLists.ltxt, as stated in one of my previous comments, so don't trust it fully :)

**Comment by dtschump** [comment]
Ah yes, I have missed it.
I still think that this is really not good to have this behavior as a default.
Particularly, because when I run `cmake` without arguments, it actually told me it was in `Release` mode.

I'm expecting then many complaints about the plug-in being slow, by people using the CMakeFile to compile it :( I'll stick with the idea that adding the -O3 specifically in the CMakeFile is a good idea.

**Comment by alvinhochun** [comment]
> Ah yes, I have missed it.
> I still think that this is really not good to have this behavior as a default.
> Particularly, because when I run cmake without arguments, it actually told me it was in Release mode.

Yes, because there is an incorrect if condition which needs to be fixed.

> I'm expecting then many complaints about the plug-in being slow, by people using the CMakeFile to compile it :( I'll stick with the idea that adding the -O3 specifically in the CMakeFile is a good idea.

Like I said, that if condition is incorrect so adding `-O3` there is not a good idea.

Specificly, when `CMAKE_BUILD_TYPE` is not set, it is expected that CMake does not add any optimization flags. I believe some packaging build setups depend on using the `CXXFLAGS` environment variable to set the compiler flags they want, so IMO forcing `-O3` when `CMAKE_BUILD_TYPE` is not set is a pretty bad idea.

**Comment by dtschump** [comment]
I see , thanks for the explanations.
This won't help me in trusting `cmake` anymore :), but if this is the usual default behavior...
If you can propose a fix for the conditional, you're welcome!

**Comment by alvinhochun** [comment]
Perhaps something like:
```
if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    message("Debug build")
    add_definitions(-D_GMIC_QT_DEBUG_)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=address")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}  -fsanitize=address") 
elseif (CMAKE_BUILD_TYPE STREQUAL "Release")
    message("Release build")
    add_definitions(-DQT_NO_DEBUG_OUTPUT)
elseif (CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    message("Release build with debug info")
    # Force optimization level -O3
    string(REPLACE "-O2" "-O3" CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
    add_definitions(-DQT_NO_DEBUG_OUTPUT)
else()
    message(WARNING "Build type not specified or unsupported!")
    add_definitions(-DQT_NO_DEBUG_OUTPUT)
endif()
```

But I am not sure if that replace will actually work. I haven't tested this, I just hand-crafted it in this reply.
