### ISSUE TITLE
Make notes selectable

### ISSUE THREAD

**Issue by Reptorian1125** [c-koi/gmic-qt#199]
Hi, there are some cases where I'd like notes selectable. In the case of Premade Palette, I'd like for those palette information to be selectable. Another case is that I have a Python source code as part of a text within Lavander Binary Map, and it'd be great if that can be moved to selectable note.

**Comment by dtschump** [comment]
Notes are already selectable.

![image](https://github.com/c-koi/gmic-qt/assets/10114565/97ba6c0e-41ce-46ca-bd79-9a9eea36f34e)

**Comment by Reptorian1125** [comment]
Oh, I don't remember it being selectable before, so I did not bother trying. Ok, I will close this.
