### ISSUE TITLE
[Krita] No display support for plug-in in Krita 3.2 (Win10)

### ISSUE THREAD

**Issue by dtschump** [c-koi/gmic-qt#20]
There is an issue reported on the `gmic-community` repo : 

https://github.com/dtschump/gmic-community/issues/92

@boudewijnrempt , maybe do you have some suggestion ?

**Comment by boudewijnrempt** [comment]
> There is an issue reported on the `gmic-community` repo : 
> 
> https://github.com/dtschump/gmic-community/issues/92
> 
> @boudewijnrempt , maybe do you have some suggestion ?

Yes, I fixed that in today's pull request. I'll redo the request
tomorrow. I thought I had updated gmic and cimg, but apparently
that failed, so I need to remove the changes related to srand.

-- 
Boudewijn Rempt | http://www.krita.org, http://www.valdyas.org
