### ISSUE TITLE
Crash with Qt6 not Qt5...

### ISSUE THREAD

**Issue by cgilles** [c-koi/gmic-qt#204]
Command line with the None plugin version:

./gmic_qt -c "samj_Barbouillage_Paint_Daub 2,2,100,0.2,1,4,1,0,8" ./DSC08800.JPG

Backtrace:

Thread 1 "gmic_qt" received signal SIGSEGV, Segmentation fault.
0x0000aaaaaabce180 in gmic_library::cimg::strunescape (str=0xfffff64cf2b0 <QByteArray::_empty> "")
    at /mnt/data/Devel/gmic-qt/../gmic/src/CImg.h:7125
7125          for (char *ns = str, *nd = str; *ns || (bool)(*nd = 0); ++nd) if (*ns=='\\') switch (*(++ns)) {
(gdb) bt
#0  0x0000aaaaaabce180 in gmic_library::cimg::strunescape (str=0xfffff64cf2b0 <QByteArray::_empty> "")
    at /mnt/data/Devel/gmic-qt/../gmic/src/CImg.h:7125
#1  0x0000aaaaaabce734 in GmicQt::HtmlTranslator::fromUtf8Escapes (str=...)
    at /mnt/data/Devel/gmic-qt/src/HtmlTranslator.cpp:60
#2  0x0000aaaaaabce394 in GmicQt::HtmlTranslator::html2txt (str=..., force=false)
    at /mnt/data/Devel/gmic-qt/src/HtmlTranslator.cpp:49
#3  0x0000aaaaaabdbee0 in GmicQt::MainWindow::retrieveFilterAndParametersFromPluginParameters (this=0xffffffffea18, hash=..., 
    parameters=...) at /mnt/data/Devel/gmic-qt/src/MainWindow.cpp:408
#4  0x0000aaaaaabdd194 in GmicQt::MainWindow::onStartupFiltersUpdateFinished (this=0xffffffffea18, status=2)
    at /mnt/data/Devel/gmic-qt/src/MainWindow.cpp:528
#5  0x0000aaaaaabeafa8 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<int>, void, void (GmicQt::MainWindow::*)(int)>::call (
    f=(void (GmicQt::MainWindow::*)(GmicQt::MainWindow * const, int)) 0xaaaaaabdcdd0 <GmicQt::MainWindow::onStartupFiltersUpdateFinished(int)>, o=0xffffffffea18, arg=0xffffffffe278) at /opt/qt6/include/QtCore/qobjectdefs_impl.h:145
#6  0x0000aaaaaabe9db0 in QtPrivate::FunctionPointer<void (GmicQt::MainWindow::*)(int)>::call<QtPrivate::List<int>, void> (
    f=(void (GmicQt::MainWindow::*)(GmicQt::MainWindow * const, int)) 0xaaaaaabdcdd0 <GmicQt::MainWindow::onStartupFiltersUpdateFinished(int)>, o=0xffffffffea18, arg=0xffffffffe278) at /opt/qt6/include/QtCore/qobjectdefs_impl.h:182
#7  0x0000aaaaaabe871c in QtPrivate::QCallableObject<void (GmicQt::MainWindow::*)(int), QtPrivate::List<int>, void>::impl (
    which=1, this_=0xaaaaab644f40, r=0xffffffffea18, a=0xffffffffe278, ret=0x0)
    at /opt/qt6/include/QtCore/qobjectdefs_impl.h:520
#8  0x0000fffff61ce460 in void doActivate<false>(QObject*, int, void**) () from /mnt/data/Devel/gmic-qt/build/libQt6Core.so.6
#9  0x0000aaaaaaafe4c4 in GmicQt::Updater::updateIsDone (this=0xaaaaab659c90, _t1=2)
    at /mnt/data/Devel/gmic-qt/build/gmic_qt_autogen/UVLADIE3JM/moc_Updater.cpp:222
#10 0x0000aaaaaac06eb0 in GmicQt::Updater::onUpdateNotNecessary (this=0xaaaaab659c90)
    at /mnt/data/Devel/gmic-qt/src/Updater.cpp:211
#11 0x0000aaaaaac1c460 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (GmicQt::Updater::*)()>::call(void (GmicQt::Updater::*)(), GmicQt::Updater*, void**) (
    f=(void (GmicQt::Updater::*)(GmicQt::Updater * const)) 0xaaaaaac06e98 <GmicQt::Updater::onUpdateNotNecessary()>, 
    o=0xaaaaab659c90, arg=0xaaaaab67d8b8) at /opt/qt6/include/QtCore/qobjectdefs_impl.h:145
#12 0x0000aaaaaac1b9cc in QtPrivate::FunctionPointer<void (GmicQt::Updater::*)()>::call<QtPrivate::List<>, void>(void (GmicQt::Updater::*)(), GmicQt::Updater*, void**) (
    f=(void (GmicQt::Updater::*)(GmicQt::Updater * const)) 0xaaaaaac06e98 <GmicQt::Updater::onUpdateNotNecessary()>, 
    o=0xaaaaab659c90, arg=0xaaaaab67d8b8) at /opt/qt6/include/QtCore/qobjectdefs_impl.h:182
#13 0x0000aaaaaac1aec0 in QtPrivate::QCallableObject<void (GmicQt::Updater::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate:--Type <RET> for more, q to quit, c to continue without paging--f
:QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0xaaaaab6429f0, r=0xaaaaab659c90, a=0xaaaaab67d8b8, ret=0x0)
    at /opt/qt6/include/QtCore/qobjectdefs_impl.h:520
#14 0x0000fffff61bcac4 in QObject::event(QEvent*) () from /mnt/data/Devel/gmic-qt/build/libQt6Core.so.6
#15 0x0000fffff79a6528 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /mnt/data/Devel/gmic-qt/build/libQt6Widgets.so.6
#16 0x0000fffff6168fb4 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /mnt/data/Devel/gmic-qt/build/libQt6Core.so.6
#17 0x0000fffff616d178 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /mnt/data/Devel/gmic-qt/build/libQt6Core.so.6
#18 0x0000fffff64361d8 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) ()
   from /mnt/data/Devel/gmic-qt/build/libQt6Core.so.6
#19 0x0000fffff5edf89c in ?? () from /lib/aarch64-linux-gnu/libglib-2.0.so.0
#20 0x0000fffff5f42998 [PAC] in ?? () from /lib/aarch64-linux-gnu/libglib-2.0.so.0
#21 0x0000fffff5edeb58 [PAC] in g_main_context_iteration () from /lib/aarch64-linux-gnu/libglib-2.0.so.0
#22 0x0000fffff6435b64 [PAC] in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /mnt/data/Devel/gmic-qt/build/libQt6Core.so.6
#23 0x0000fffff6176f18 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /mnt/data/Devel/gmic-qt/build/libQt6Core.so.6
#24 0x0000fffff6171dcc in QCoreApplication::exec() () from /mnt/data/Devel/gmic-qt/build/libQt6Core.so.6
#25 0x0000aaaaaabc7188 in GmicQt::run (interfaceMode=GmicQt::UserInterfaceMode::Full, parameters=..., 
    disabledInputModes=std::__cxx11::list = {...}, disabledOutputModes=std::__cxx11::list = {...}, dialogWasAccepted=0x0)
    at /mnt/data/Devel/gmic-qt/src/GmicQt.cpp:205
#26 0x0000aaaaab11bce4 in main (argc=4, argv=0xfffffffff108) at /mnt/data/Devel/gmic-qt/src/Host/None/host_none.cpp:466
(gdb) f 4
#4  0x0000aaaaaabdd194 in GmicQt::MainWindow::onStartupFiltersUpdateFinished (this=0xffffffffea18, status=2)
    at /mnt/data/Devel/gmic-qt/src/MainWindow.cpp:528
528       retrieveFilterAndParametersFromPluginParameters(hash, pluginParametersCommandArguments);

This append with filter tree view is populated when you pass a gmic command from the command line.

The Qt5 do not crash, Qt6 yes, probably due to the manner of Qt to handle data in memory with the QByteArry in GmicQt::HtmlTranslator::fromUtf8Escapes().

With some hacking, the crash appear when str argument is empty from GmicQt::HtmlTranslator::fromUtf8Escapes(). This kind of patch fix the problem:

diff --git a/src/HtmlTranslator.cpp b/src/HtmlTranslator.cpp
index 1421fc9..f4f68ac 100644
--- a/src/HtmlTranslator.cpp
+++ b/src/HtmlTranslator.cpp
@@ -56,6 +56,7 @@ bool HtmlTranslator::hasHtmlEntities(const QString & str)
 
 QString HtmlTranslator::fromUtf8Escapes(const QString & str)
 {
+  if (str.isEmpty()) return str;
   QByteArray ba = str.toUtf8();
   gmic_library::cimg::strunescape(ba.data());
   return QString::fromUtf8(ba);

Best

Gilles Caulier

**Comment by c-koi** [comment]
Thanks. Applying your patch...
