### ISSUE TITLE
Error using Extract Foreground Filter with Gimp

### ISSUE THREAD

**Issue by JohnnyWalker7** [c-koi/gmic-qt#211]
Im using gimp 2.10.38 and gmic-qt 3.4.2 for gimp 2.10
When I'm using the "Extract foreground Filter [Interactive]" with the default settings I get the following error

![image](https://github.com/user-attachments/assets/c1534825-43a7-4a63-8b04-ee06d5c97649)

**Comment by JohnnyWalker7** [comment]
the current gmic pre release 3.4.3 has this bug too

**Comment by dtschump** [comment]
Fixed with https://github.com/GreycLab/gmic/commit/05819d5be970fd024bd0360a97d979b6f7c0c39a
Filters have been uploaded and fix should be available after pushing the "Update Filters" button.

**Comment by JohnnyWalker7** [comment]
Thank you! After updating the Filters everything did work as expected.
