### ISSUE TITLE
Allow users to switch the language of interface

### ISSUE THREAD

**Issue by ZX-WT** [c-koi/gmic-qt#24]
![2017-09-01 16 41 49](https://user-images.githubusercontent.com/10883749/29962124-8f6337e2-8f34-11e7-999e-66ed99f414c9.png)

I am using the 3.2.1 appimages of krita.

I think it detects the locale of my os, traditional Chinese, and it decided to switch to simplified Chinese. I checked the source and find out that there is no traditional Chinese available, I assume it is some kind of fallback to simplified Chinese.

I think there should be an option to switch the language of the interface.

**Comment by ZX-WT** [comment]
#25 
I don't know the difficulty of implementing the language option but I added traditional Chinese to reduce the awkwardness. :)

**Comment by c-koi** [comment]
This choice is now possible in the settings dialog.
It should be available in the next pre-release (after cef74bfcabf827e8575516ad07c4aa9ffdb85860)

**Comment by ZX-WT** [comment]
nice, maybe this issue can be closed.
