### ISSUE TITLE
GMIC plugin for Gimp fails to compile from git source on Debian sid.

### ISSUE THREAD

**Issue by xaosfiftytwo** [c-koi/gmic-qt#30]
Using cmake, module TreeView.cpp does not get compiled, resulting in 'undefined reference to `TreeView::TreeView(QWidget*)' when linking CXX executable gmic_gimp_qt.

Attached make.log

[build-gmic.log](https://github.com/c-koi/gmic-qt/files/1443095/build-gmic.log)

**Comment by c-koi** [comment]
Thanks for reporting.
Fixed by c5b6b9f5892ea1f6d312496a9c538cdf9992d44f
