### ISSUE TITLE
Make tags the same as versions

### ISSUE THREAD

**Issue by AMDmi3** [c-koi/gmic-qt#35]
E.g. `v2.2.0` or `2.0.0` (not `220`) tag for `2.2.0` version. Otherwise it seem to confuse people: https://repology.org/metapackage/gmic-qt/information

**Comment by c-koi** [comment]
The NNN syntax (instead of N.N.N) conforms with the one used in the dtschump/gmic repository.
Try to report your issue here: https://github.com/dtschump/gmic/issues

**Comment by dtschump** [comment]
Will be done like this in next version. Thanks for the suggestion.

**Comment by AMDmi3** [comment]
Thank you both!
