### ISSUE TITLE
no global settings I can find for qt interface

### ISSUE THREAD

**Issue by AlexsaniKY** [c-koi/gmic-qt#37]
I used the logfile in the gtk version to see the cli commands used to generate effects, and I intended recently to parse it with some simple python scripts for batch file processing.  Pretty simple, look for lines with 'apply' in the first segment, parse out the command and args, keep track of them in a command list and you have a sequence of actions to batch process a whole photoshoot.

So I found out the gtk version is deprecated and downloaded the qt version and I'm hitting some massive impediments, which if it requires me to fix in a branch and merge later or just keep my own version somewhere publicly accessible I can live with that.

The issues:

- I can't seem to find a way to change the default (or global) settings for output messages to log the actions to a file, it would seem I have to literally change the settings for each and every single effect to have the output messages get sent somewhere I can parse them.

~~- When I open the logfile, it has no distinguishing features between lines that were "previewed" in the QT editor vs applying them to the GIMP window.  This completely prevents me from parsing the logfile for completed actions vs my tweaking values to find settings I like.~~

My desired workflow would be to open an image from a shoot in GIMP, use gmic-qt plugin to alter the image in stages, run my script to parse the logfile into discrete steps which I could apply to all images. 
 ~~I plan more features but if this part isn't possible it ruins the whole project.  What really kills me is this would have been nearly trivial in the gtk version but in this version I see no way to directly do these things.~~

**Comment by AlexsaniKY** [comment]
I revisited the issue, it does appear the effects do have a '_preview' at the end I can filter for as long as that is true for all effects.

But I do still need some way to globally set effects to have Output Messages set to "Verbose (logfile)" without manually setting each effect in the UI.

**Comment by dtschump** [comment]
That's interesting indeed. Parsing the log file was not something we had in mind to be honest :)
I suppose @c-koi will be able to fix this as soon as he's back from vacations !
Be careful, G'MIC preview command for a filter **generally** ends up with `_preview`, but this is not always the case !

**Comment by AlexsaniKY** [comment]
yeah I caught that, my bad.  If you know of any filters that don't have '_preview' suffix or a different argument length, please let me know which ones or where that information is.  My python script so far is making a pretty direct assumption on that format being consistent as is
```statements = str.split(line)
		if len(statements)==6:
			if statements[1] == 'Command:' and statements[4][-8:] != '_preview':
				commands.append(statements[-2:])```
which appears to work for the few effects I tried it with

My plans are to strip applied commands from the log, save a backup of the log and clear it, save the commands in a txt as filter, args pairs and index them.  Keep a folder of the files to process and a file saying what the current state of each one is in the command chain for the output folder, including some way of letting subsets of the image directory have an extra step applied (say some of the pictures are darker so they get the same noise filtering and color temperature correction but get some gamma correction before the other steps later).  So each image would have an effect chain I could call individually with calls to subprocess and let them be reviewed in phases but also applied directly through the whole chain as one call for a final output (so they wouldn't degrade by hitting jpg compression every time they did one effect call).

I'll put a liberal license on it and when it works, I'm fine with trying to get it cross-platform and letting the gmic community have at it.

I noticed that the preferences seem to be stored as a compressed json file, if I had someone point me to the documentation I could probably rig something to strip all filter names, and apply a output verbose to logfile setting which is probably the quickest fix.

**Comment by c-koi** [comment]
Since 1769eb0, messages are now of the form:
```
[gmic_gimp_qt]./preview/ v -99 fx_balance_gamma_preview 0,0,127,1,0
```
or
```
[gmic_gimp_qt]./apply/ v -99 fx_balance_gamma 0,0,127,1,0
```
That should ease parsing...
Furthermore, the settings for the output messages are now global (b981ddf) and no longer memorized on a per filter basis. They may be found in the settings dialog (943b5e0).

**Comment by c-koi** [comment]
@AlexsaniKY Last comment now applies to the last stable release (2.2.3)

**Comment by AlexsaniKY** [comment]
That sounds awesome, thank you for the prompt response and solution.  Will this need to be compiled by myself or do you know which sites will already have a recently compiled version?

**Comment by c-koi** [comment]
See the [download section](https://gmic.eu/download.shtml) at gmic.eu.

**Comment by AlexsaniKY** [comment]
well I didn't see any information on the installer/zips as to anything except gmic version so I'll assume you mean I will need to compile it myself for now
