### ISSUE TITLE
CentOS7: Krita 4.0.4 + gmic_krita_qt 2.3.0/2.2.3 - QSharedMemory::attach

### ISSUE THREAD

**Issue by stascrash** [c-koi/gmic-qt#44]
Hello, i am running CentOS7 with kernel 3.10.0-514.26.2.el7.x86_64.
I am trying to make Krita work with Stable and PRE versions of Gmic. 
I have compiled from sources  following the guide using Qt5.6.1.
When i load the plugin via Filter-view in Krita, in terminal i have:
`Plugin started true QProcess::ProcessState(Running)                         
gmic-qt: socket Key: "{ea3730a8-37ce-48e2-8242-3379aa1b1de2}"                   
connected                            
Received "command=gmic_qt_get_image_size\nmode=1"
Sending "1600,1200"            
connected                            
Received "command=gmic_qt_get_cropped_images\nmode=1\ncroprect=0,0,1,1"                                  
prepareCroppedImages() "" QRectF(0,0 1x1) 1
Converting node "Layer 2" QRect(0,0 1600x1200)
"key_{cb707798-7e65-4b0a-b4f3-f8883f577c5c},4c617965722032,1600,1200\n"
Sending "key_{cb707798-7e65-4b0a-b4f3-f8883f577c5c},4c617965722032,1600,1200\n"
        gmic-qt: Could not attach to shared memory area. 5 "QSharedMemory::attach (shmget): doesn't exist"
gmic-qt: Could not attach to shared memory area. 5 "QSharedMemory::attach (shmget): doesn't exist"
`

**Comment by dtschump** [comment]
@boudewijnrempt may help about Krita issues.

**Comment by boudewijnrempt** [comment]
If CentOS doesn't support shared memory, then the gmic-qt plugin cannot work. I don't have centos here, so I don't know how that is configured by default.
