### ISSUE TITLE
make gimp and make gmic-qt throws an error on MacOS 10.13.5 MacPorts 2.5.2

### ISSUE THREAD

**Issue by karo11** [c-koi/gmic-qt#45]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -O2 -Ofast -s -std=gnu++11  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC -Dcimg_use_cpp11=1 -Dcimg_use_fftw3 -Dcimg_use_zlib -Dgmic_build -Dcimg_use_abort -Dgmic_is_parallel -Dcimg_use_curl -Dcimg_use_png -Dcimg_use_rng -Dcimg_appname=\"gmic\" -Dgmic_prerelease=\"180617\" -Dcimg_display=1 -DGMIC_HOST=standalone -Dgmic_gui -Dgmic_build -Dgmic_is_parallel -Dcimg_use_abort -Dcimg_use_vt100 -DQT_NO_DEBUG_OUTPUT -D_IS_MACOS_ -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -Isrc -I../gmic/src -I/opt/local/include -I/opt/local/include/libpng16 -I/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers -I/opt/local/libexec/qt5/lib/QtGui.framework/Headers -I/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers -I/opt/local/libexec/qt5/lib/QtCore.framework/Headers -I.moc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I.ui -I/opt/local/libexec/qt5/mkspecs/macx-clang -F/opt/local/libexec/qt5/lib -o .obj/FilterSyncRunner.o src/FilterSyncRunner.cpp
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
src/FilterSyncRunner.cpp:41:3: error: use of undeclared identifier 'setStackSize'
  setStackSize(8 * 1024 * 1024);
  ^
1 error generated.
make[1]: *** [Makefile:3203: .obj/FilterSyncRunner.o] Fehler 1
make[1]: Verzeichnis „/Volumes/mbxxxxSD1/Users/xxxx/sw/gmic-qt“ wird verlassen
make: *** [Makefile:528: gmic_qt] Fehler 2

**Comment by c-koi** [comment]
Fixed by ae1c18d2e7acff16903bf284105fbc4b666fd5d5

**Comment by karo11** [comment]
Ok, thank you!

By the way, point() parameters of gmic scripts in gmic_gimp_qt (gmic 2.3.0) are functional in Gimp 2.10.2 under MacOS 10.13 and MacPorts 2.5.2, very good!

**Comment by dtschump** [comment]
Thanks Karsten, your feedback is really important for us since we don't have a Mac to test here at the lab. Feel free to report any strange behavior before the final stable release of version 2.3.0 :)

**Comment by karo11** [comment]
David, what about sequences (arrays)) of point() with extend/changeable number? 
The point()GUI parameter is a really good step forward, still hunger comes with eating!

**Comment by dtschump** [comment]
You can already define 'optional' points : 
`Point = point(50,50,1)`

Optional points can be added by clicking on the little '+' icon just beside the point coordinates in the parameter pane.
