### ISSUE TITLE
Cursor change after point() movements 

### ISSUE THREAD

**Issue by karo11** [c-koi/gmic-qt#46]
Seemingly in "Spherize", "Flower", "Euclidean - polar" and "Kaleidoscope [polar/blended]" after some movements of Center the cursor does not change back to default!

For "Flower" it would be good to fix the former distance and angle, (white point moves the red too)!
![2018-06-20_12-13-47](https://user-images.githubusercontent.com/1217623/41652869-af3bb482-7484-11e8-985b-5c8cf0d470d9.png)

This is
![image](https://user-images.githubusercontent.com/1217623/41652774-5dc1ab48-7484-11e8-81b5-119a92a57906.png)

**Comment by dtschump** [comment]
Hi Karsten, I don't really understand. Do you mean the cursor icon of the mouse pointer ?
What aspect does it keep ?

**Comment by karo11** [comment]
David, what should I say? During processing the cursor changes to the one in my snapshot. After some trials it does not change back to the default. If you don't experience it, its maybe a qt Mac specify.

**Comment by dtschump** [comment]
No, that's OK. We got the same problem here on our machine, so it's not MacOS specific.
@c-koi is working on a fix. Thanks again for your useful feedback !

**Comment by c-koi** [comment]
Should be fixed by f5cae59402d8f386801bae267c6c14f1c042656c
