### ISSUE TITLE
timeout handling

### ISSUE THREAD

**Issue by karo11** [c-koi/gmic-qt#47]
Calling gmic scripts with "-x" (external programs)calls  in gmic_gimp_qt delivers immediate timeout independent of the time set.

This is MacOS 10.14.5/Gimp 2.10 /gmic 2.3.2_pre#180626

**Comment by dtschump** [comment]
do you mean in the preview window of the filter ?

**Comment by karo11** [comment]
yes

**Comment by karo11** [comment]
Ok, I found that this behavior appears in cases where an executable (called via "x" in gmic scripts) was not found (Gimp internal PATH) or was not executable.
