### ISSUE TITLE
Colorize (interactive) Filter Doesn't complete when using i3wm

### ISSUE THREAD

**Issue by Algorithmus** [c-koi/gmic-qt#51]
Steps to reproduce
1 Grab any old image with "lineart"; can even be very simple.
2 Choose the colorize [interactive] filter and add control points. (I used the Lineart and Image + Colors (2 layers) option)
3 Finish and press Enter.

Expected results: gmic finishes processing the points and you get the image back.
What happens: gmic is stuck in processing with the progress bar at the bottom; nothing happens. You can still cancel it, but the image remains unaltered.

Sometimes works the first time; but after that, it stops working. I've only ever been able to do this when using i3wm; doesn't happen in XFCE, for example.

Might also happen with other interactive filters. I tried color mask [interactive] and the same thing happens.

**Comment by leiserfg** [comment]
I had a similar issue with `stylize` when preview progression is on.

**Comment by leiserfg** [comment]
I fixed it by adding a rule in order to make the gmic-qt window float.
