### ISSUE TITLE
make install cannot find file cs.qm

### ISSUE THREAD

**Issue by dmaugis** [c-koi/gmic-qt#53]
the build is ok, but install failed for cs.qm file missing.

`Builds/gmic-qt$ make -j5
...
[100%] Built target gmic_gimp_qt
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:49 (file):
  file INSTALL cannot find "/home/dmaugis/Builds/gmic-qt/cs.qm".
Makefile:85: recipe for target 'install' failed
make: *** [install] Error 1`

**Comment by c-koi** [comment]
No more errors thanks to this fix by Jehan : 91f92ba589d6559541d5dfacf39dab4e0faaa106
However, be aware that install is not taken care of properly by the CMakeLists.
