### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by boudewijnrempt** [c-koi/gmic-qt#57]
Someone is complaining that krita's gmic-qt plugin cannot download updates:

https://bugs.kde.org/show_bug.cgi?id=401346

What could be the cause of that? I have no idea...

**Comment by boudewijnrempt** [comment]
Is that already in a release? If so, I'll update our gmic-qt plugin for the next release, which is planned for this wednesday or thursday.

**Comment by dtschump** [comment]
No, this will be in next version *2.4.2* of G'MIC. Sorry :(
