### ISSUE TITLE
Can the G'MIC plugins output and re-input files?

### ISSUE THREAD

**Issue by ornithologistnightmare** [c-koi/gmic-qt#60]
I've been trying to implement a JIFF ('JPEG') glitch script in G'MIC and the quickest way to do it is to mess with the data of a JPEG file that's already been saved from within the GIMP plugin. I've asked about it in [a giant thread on discuss.pixls.us](url) and I've got a no from a very experienced G'MIC user, though they say that it's possible in the CLI interface. It would be more convenient to have input and output operations within the plugin so that one can make images similar to the one demonstrated [here](https://snorpey.github.io/jpg-glitch/).

**Comment by c-koi** [comment]
See [command line options](https://github.com/c-koi/gmic-qt/blob/master/STANDALONE.md) of the standalone version.
