### ISSUE TITLE
Film emulation filters is missing in version 2.5.3?

### ISSUE THREAD

**Issue by Hund** [c-koi/gmic-qt#68]
I use Gentoo Linux and updated from version 2.4.5 to 2.5.3 today and noticed that the film emulation filters was missing?

What is going on?

**Comment by dtschump** [comment]
Film emulation filters have been gathered into two filters : 

`Colors / Color Presets` and `Colors / Simulate Film`.

**Comment by Hund** [comment]
I see. How do I make a preview with all the options like before?

**Comment by dtschump** [comment]
It's not possible anymore. **But**, I'm working on this, and it will be probably available again in a few days.

**Comment by Hund** [comment]
Thanks! :)

**Comment by Hund** [comment]
It's been a few months and I'm still eagerly waiting for the preview feature. Any news?

**Comment by Droner852** [comment]
> It's been a few months and I'm still eagerly waiting for the preview feature. Any news?

Hi there, Not sure if you have gotten the problem solved.  If not, you may try to use Colous/Apply External CLUT.  It definitely works as Film Emulation filers.

**Comment by Hund** [comment]
It's been about 1,5 years now. I'm still waiting. :)
