### ISSUE TITLE
Can't build on Debian 9

### ISSUE THREAD

**Issue by Sunderland93** [c-koi/gmic-qt#7]
Hi. I try to build G'MIC Qt on my Debian 9. Error is:

```
Project MESSAGE: GMIC PATH ../gmic/src
Project MESSAGE: Prerelease date is 170624
Project MESSAGE: Linux platform
Project MESSAGE: Target host software is GIMP
Project MESSAGE: OpenMP enabled
Project MESSAGE: Release build
Project ERROR: fftw3 development package not found
```
but libfftw3-dev is installed. What's wrong?

**Comment by c-koi** [comment]
This must be a misleading message from qmake.
It's certainly pkg-config which is actually missing on your system.

**Comment by Sunderland93** [comment]
Yes, the reason is pkg-config :) Thanks!
