### ISSUE TITLE
Is there a way to reset a filter parameters to (sane) defaults.

### ISSUE THREAD

**Issue by boffi** [c-koi/gmic-qt#72]
Dear Developers,
sometimes I play so much with a filter settings to find my self _painted_ in a corner (ahah, painted!).
At that point the only way that I know to restart my game using sane defaults is to restart the, say, _host_ of G'MIC-Qt (in my case The Gimp) because closing and restarting the Qt interface reloads the modified settings again and again (note that restarting The Gimp resets _all_ filters settings):
- is it possible to tell the Qt interface to reload the defaults? or,
-  is it possible to introduce such a mechanism?

If it's possible to introduce such a mechanism, I suggest that it acts on a filter by filter basis, possibly with the option of a global reset but this, imho, is rather a secondary issue because we can always restart the _host_.
Nice to have G'MIC, thank you very much  ֎ g

**Comment by dtschump** [comment]
![reset_params](https://user-images.githubusercontent.com/10114565/63175875-2c4c8700-c045-11e9-967c-42c4681c3731.png)

**Comment by dtschump** [comment]
Sorry, the text has disappeared :)
There is a "reset" button beside each filter title, and pressing it just reset the filter params to their default values.

**Comment by boffi** [comment]
Exactly so... I'm very sorry about the noise.
