### ISSUE TITLE
Open more than one layer in GIMP

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [c-koi/gmic-qt#79]
What I have done:
- Open an image in GIMP
- Open a second image (other scale or same scale) as a second layer
- Select both layers with "chaining" them
- open GMIC-plugin and choose "Stylize" with "Custom Style (Top Layer)" setting as "Style"

What I expect: The bottom layer of my image get stylized like the top layer.

What happens instead: "Preview warning: At least two layers are required when specifying a custom style"

Did I do something wrong or is that an error/limitation in the plugin?

GIMP version 2.10.12
gmic version 2.7.1
System: Manjaro Linux

**Comment by dtschump** [comment]
Have you set the `Input Layers` option to `All` ? (in my screenshot, in French : 'Calques en entrée-> Tous').
![stylize_all_layers](https://user-images.githubusercontent.com/10114565/64697053-404aa380-d4a0-11e9-9f5b-3815740b5d2c.png)

**Comment by seasnakes** [comment]
> Have you set the `Input Layers` option to `All` ? (in my screenshot, in French : 'Calques en entrée-> Tous'). ![stylize_all_layers](https://user-images.githubusercontent.com/10114565/64697053-404aa380-d4a0-11e9-9f5b-3815740b5d2c.png)

Do you know how to Input Multiple Images in G'MIC-Qt Standalone Version?    The input window seems to only allow selecting a single image
![image](https://github.com/user-attachments/assets/8be0fd4d-00b3-479a-a4ff-3eaeda85f683)

**Comment by dtschump** [comment]
The only way I know is to invoke `gmic_qt` from the command line with the `-l` option:

~~~
$ gmic_qt -l ~/work/img/*.jpg
~~~

![image](https://github.com/user-attachments/assets/1371f56a-b3e2-4a20-92e0-00da25044711)
