### ISSUE TITLE
Why is GIMP the default host in the README example?

### ISSUE THREAD

**Issue by ShalokShalom** [c-koi/gmic-qt#8]
Isnt the Qt port supposed to work with Qt programms like Krita? 
Why should i build gmic-qt with GIMP?

![screenshot_20170710_222705](https://user-images.githubusercontent.com/6344099/28038360-ea9c012e-65be-11e7-9265-229e76d00477.png)

**Comment by dtschump** [comment]
`qmake HOST=krita` will do it, without any GTK dependency.

**Comment by ShalokShalom** [comment]
Thanks a lot. I changed the title, so maybe you can answer on that one as well?
Your https://github.com/c-koi/gmic-qt/blob/master/gmic_qt.pro is actually showing what you are telling me, i was to quick with posting me former question. Sorry for the confusion :)

**Comment by dtschump** [comment]
There are no particular reasons to have `gimp` as default. Probably because that is the most requested plug-in for now.

**Comment by ShalokShalom** [comment]
For the qt port as well? Ok, thanks.

**Comment by dtschump** [comment]
It's not really a "qt-port". It is a rewrite of the plug-in from scratch (using Qt), with lot of new features, so this is the recommended plug-in to install even on GIMP.
The GTK version should be considered as obsolete and not used anymore.
