### ISSUE TITLE
Please move translation (.qm) files into the executable's embedded Qt resources

### ISSUE THREAD

**Issue by yurivict** [c-koi/gmic-qt#83]
Currently it installs one executable and many ```.qm``` files. When different flavors of gmic-qt (gimp/krita) are installed, these ```.qm``` files conflict with each other.

This conflict would go away if these files would move into the executable itself.

Speaking on behalf of the FreeBSD port ```graphics/gmic-qt```.

**Comment by c-koi** [comment]
.qm files have always been included as resources in the executable
64cdd2cdd416ec43171753eddf55a7b3fda0d33b removes the related install line in CMakeLists.txt
