### ISSUE TITLE
Allow hosts to check if the user canceled the plugin

### ISSUE THREAD

**Issue by 0xC0000054** [c-koi/gmic-qt#86]
Currently there is no way for a host the know if the user canceled the dialog, this can cause confusing behavior for users.

For example, in the GIMP and Paint.NET plugins if a user clicks the Apply button followed by Cancel it behaves as if the user clicked Ok.
This requires the user to undo the applied G'MIC effect after the G'MIC-Qt plugin has been closed.

The API should provide a method for the host to determine if the user exited the dialog by pressing the Ok button, any other exit method will be treated as if the dialog was canceled.

**Comment by c-koi** [comment]
a4af7410500fd6e9c8ae40e102fb0eff14a7d04d introduces such a test function
(GIMP does not automatically undo all applied modifications even if the plugin returns a GIMP_PDB_CANCEL status.)

**Comment by 0xC0000054** [comment]
Thanks, I can confirm that it works for the Paint.NET host.

Closing this issue.

**Comment by 0xC0000054** [comment]
After further testing it appears that `pluginDialogWasAccepted()` also returns false when the Ok button is pressed.
This occurs even if Apply is pressed before Ok.

**Comment by c-koi** [comment]
Should be fixed by d40db0f4ea35e2aca384c370c6d9d0e2affe251f

**Comment by 0xC0000054** [comment]
> Should be fixed by [d40db0f](https://github.com/c-koi/gmic-qt/commit/d40db0f4ea35e2aca384c370c6d9d0e2affe251f)

That fixes the issue.
