### ISSUE TITLE
Provide desktop file

### ISSUE THREAD

**Issue by City-busz** [c-koi/gmic-qt#88]
Please include a .desktop file that meets the [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/), so the application could be appear in the application launchers on Linux.

**Comment by c-koi** [comment]
See 1c01882210aa3558248dc9cfcd13e1d3705943e4

**Comment by dtschump** [comment]
Just made https://github.com/dtschump/gmic/commit/f6f3af03e4d9dae25136c56f01aa67b88c4ae5b0 
Building .deb packages now to check.
