### ISSUE TITLE
Questions about translation

### ISSUE THREAD

**Issue by tysontan** [c-koi/gmic-qt#91]
Hi, I'm Tyson Tan from Krita's simplified Chinese community. May I ask how do I contribute to the translation of gmic and gmic-qt? I only see a few translation files in the repository that contain only the base UI strings, while all the filters together must have thousands of strings to translate. I tried to find related documentation but with no luck. Can you help me? Thanks!

**Comment by c-koi** [comment]
You may submit PRs for the translation/*.ts files, or see this [HOWTO](https://github.com/c-koi/gmic-qt/blob/master/translations/filters/HOWTO.md) for filters.
